<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/CleaningNotNullValues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame ({
        'Sex': ['M', 'F', 'F', 'D', '?'],
        'Age': [29, 30, 24, 290, 25],
})

df

  Sex  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

How can we clean the not-misisng values but clearly invalid values?

##**Finding Unique Values**

We start by analizing the variety of value spresent.For that, we use the `unique()` method.

In [3]:
df['Sex'].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [4]:
df['Sex'].value_counts()

Sex
F    2
M    1
D    1
?    1
Name: count, dtype: int64

You can use the `replace` function to replace values like `'D'` and `'?'`.

In [5]:
df['Sex'].replace({'D': 'F', 'N': 'M'})

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

If you have many columns to replace, you could apply it at "DataFrame" level

In [6]:
df.replace({
    'Sex': {
        'D' : 'F',
        'N' : 'M'
    },
    'Age': {
        290 : 29
    }
})

  Sex  Age
0   M   29
1   F   30
2   F   24
3   F   29
4   ?   25

What if you'd like to remove all the extra 0s from the ages columns? (example, 150 > 15, 490 > 49).

We can combine boolean selection with the operation:

In [7]:
df[df['Age'] > 100]

  Sex  Age
3   D  290

And we can now just divide by 10:

In [10]:
# selecione, na coluna Age, somente as linhas em que Age > 100.

# df['Age'] > 100 → escolhe somente as linhas em que Age é maior que 100
# 'Age' → escolhe somente a coluna Age
df.loc[df['Age'] > 100, 'Age'] = df.loc[df['Age'] > 100, 'Age'] / 10

In [11]:
df

  Sex  Age
0   M   29
1   F   30
2   F   24
3   D   29
4   ?   25

---