<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/Pandas_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    'GPD': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GPD', 'Surface Area', 'HDI', 'Continent'])

In [4]:
df

   Population       GPD  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

`Data Frame`s also have indexes

In [5]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [6]:
df

                Population       GPD  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [7]:
df.columns # quais colunas temos

Index(['Population', 'GPD', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [8]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [9]:
df.info() #informação sobre a estrutura do Data Frame

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Population    7 non-null      float64
 1   GPD           7 non-null      int64
 2   Surface Area  7 non-null      int64
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object
dtypes: float64(2), int64(2), object(1)
memory usage: 636.0+ bytes

In [10]:
df.size

35

In [11]:
df.shape

(7, 5)

In [12]:
df.describe() # resumo das estatísticas
#somente colunas numéricas

       Population           GPD  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [13]:
df.dtypes

Population      float64
GPD               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [14]:
df.dtypes.value_counts()

float64    2
int64      2
object     1
Name: count, dtype: int64

---

##**Indexing, Selection and Slicing**
Individual columns can be selected with regular indexing. Each column is represented as a `Series`.

In [15]:
df

                Population       GPD  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [16]:
df['Population'] #coluna individual selecionada

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

Note that the index of the returned Series is the same as the DataFrame one. And its name is the name of the column. If you're working on a notebook and want to see a more DataFrame-like format, you can use the `to_frame()` method.

In [17]:
df['Population'].to_frame()

                Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

Multiple columns can also be selected.

In [18]:
df[['Population', 'GPD']]  # nesse caso o resultado é outro DataFrame.

                Population       GPD
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

Slicing works differently, it acts at 'row level' and can be counter intuitive.

In [19]:
df[1:3]  # faz um fatiamento por posição e retorna as linhas que estão nas posições 1 e 2.

         Population      GPD  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

Row level selection works better with `loc` and `iloc.`
`loc` selects rows matching the given index:

In [20]:
df.loc['Italy'] # seleciona uma linha pelo rótulo do índice

Population       60.665
GPD             2167744
Surface Area     301336
HDI               0.873
Continent        Europe
Name: Italy, dtype: object

In [21]:
df.iloc[-1]

Population       318.523
GPD             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [22]:
df.loc['France':'Italy']

         Population      GPD  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

As a second "argument" you can pass the column(s) you'd like to select.

In [23]:
df.loc['France':'Italy', 'Population']

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [24]:
df.loc['France':'Italy', ['Population', 'GPD']]

         Population      GPD
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

iloc works with the (numeric) "position" of the index.

In [25]:
df

                Population       GPD  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [26]:
df.iloc[0]

Population       35.467
GPD             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [27]:
df.iloc[-1]

Population       318.523
GPD             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [28]:
df.iloc[[0, 1, -1]]

               Population       GPD  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [29]:
df.iloc[1:3, 3]

France     0.888
Germany    0.916
Name: HDI, dtype: float64

In [31]:
df.iloc[1:3,[0, 3]]  #index e colunas desejadas

         Population    HDI
France       63.951  0.888
Germany      80.940  0.916

In [32]:
df.iloc[1:3, 1:3]

             GPD  Surface Area
France   2833687        640679
Germany  3874437        357114

Recomenda-se sempre usar `loc` e `iloc`.

---