<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/PandasIntroductionipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

##**Pandas Series**

We'll start analyzing the "The Group of Seven".
We'll use a panda.Series object

In [2]:
# In millions
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [3]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

Series can have a `name`, to better document the purpose of the series.

In [4]:
g7_pop.name = 'G7 population in millions'

In [5]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: G7 population in millions, dtype: float64

Series are similar to numpy arrays.

In [6]:
g7_pop.dtype

dtype('float64')

In [7]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

A series has a `index`

In [8]:
g7_pop[0]

np.float64(35.467)

In [9]:
g7_pop[1]

np.float64(63.951)

In [10]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [11]:
g7_pop.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [12]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

We can create Series out of dictionaries

In [14]:
pd.Series({
    'Canada': 35.467,
    'France': 63.951,
    'Germany': 80.94,
    'Italy': 60.665,
    'Japan': 127,
    'United Kingdom': 64.511,
    'United States': 318.523
}, name='G7 Population in millions')

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.000
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [15]:
pd.Series(
    [35.467, 63.951, 80.94, 60.665, 127, 64.511, 318.523],
    index=['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
    name='G7 Population in millions'
)

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.000
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

Create Series out of other Series

In [16]:
pd.Series(g7_pop, index=['France', 'Germany', 'Italy', 'Spain'])

France     63.951
Germany    80.940
Italy      60.665
Spain         NaN
Name: G7 population in millions, dtype: float64

---