<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/PandasCreatingColumns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    'GPD': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GPD', 'Surface Area', 'HDI', 'Continent'])

In [3]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [4]:
df

                Population       GPD  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

---

##**Creating columns from others columns**

In [5]:
df[['Population', 'GPD']]

                Population       GPD
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [6]:
df['GPD']/ df['Population']

Canada            50339.385908
France            44310.284437
Germany           47868.013343
Italy             35733.025633
Japan             36221.712406
United Kingdom    45729.239975
United States     54464.120330
dtype: float64

In [7]:
df['GPD per capita'] = df['GPD']/ df['Population']

In [8]:
df

,Population,GPD,Surface Area,HDI,Continent,GPD per capita
Canada,35.467,1785387,9984670,0.913,America,50339.385908
France,63.951,2833687,640679,0.888,Europe,44310.284437
Germany,80.940,3874437,357114,0.916,Europe,47868.013343
Italy,60.665,2167744,301336,0.873,Europe,35733.025633
Japan,127.061,4602367,377930,0.891,Asia,36221.712406
United Kingdom,64.511,2950039,242495,0.907,Europe,45729.239975
United States,318.523,17348075,9525067,0.915,America,54464.120330

---

##**Statistical info**

In [9]:
df.head()

         Population      GPD  Surface Area    HDI Continent  GPD per capita
Canada       35.467  1785387       9984670  0.913   America    50339.385908
France       63.951  2833687        640679  0.888    Europe    44310.284437
Germany      80.940  3874437        357114  0.916    Europe    47868.013343
Italy        60.665  2167744        301336  0.873    Europe    35733.025633
Japan       127.061  4602367        377930  0.891      Asia    36221.712406

In [11]:
df.describe()

       Population           GPD  Surface Area       HDI  GPD per capita
count    7.000000  7.000000e+00  7.000000e+00  7.000000        7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429    44952.254576
std     97.249970  5.494020e+06  4.576187e+06  0.016592     6954.983875
min     35.467000  1.785387e+06  2.424950e+05  0.873000    35733.025633
25%     62.308000  2.500716e+06  3.292250e+05  0.889500    40265.998421
50%     64.511000  2.950039e+06  3.779300e+05  0.907000    45729.239975
75%    104.000500  4.238402e+06  5.082873e+06  0.914000    49103.699626
max    318.523000  1.734808e+07  9.984670e+06  0.916000    54464.120330

In [12]:
population = df['Population']

In [13]:
population.min(), population.max()

(35.467, 318.523)

In [14]:
population.sum()

np.float64(751.118)

In [17]:
population.sum()/ len(population)

np.float64(107.30257142857144)

In [18]:
population.mean()

np.float64(107.30257142857144)

In [19]:
population.std()

97.24996987121581

In [20]:
population.median()

64.511

In [21]:
population.describe()

count      7.000000
mean     107.302571
std       97.249970
min       35.467000
25%       62.308000
50%       64.511000
75%      104.000500
max      318.523000
Name: Population, dtype: float64

In [23]:
population.quantile(.25)  # encontra o valor abaixo do qual estão aproximadamente 25% dos dados.

np.float64(62.308)

In [24]:
population.quantile([.2, .4, .6, .8, 1])

0.2     61.3222
0.4     64.1750
0.6     74.3684
0.8    117.8368
1.0    318.5230
Name: Population, dtype: float64

---