<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/PandasIndexingAndConditionalSelection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

##**Indexing**

In [10]:
# In millions
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [11]:
g7_pop.name = 'G7 population in millions'

In [12]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: G7 population in millions, dtype: float64

In [15]:
g7_pop.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [16]:
g7_pop['Canada']

np.float64(35.467)

In [17]:
g7_pop['Japan']

np.float64(127.061)

Numeric positions can also be used, witch the `iloc` atribute

In [18]:
g7_pop.iloc[0]

np.float64(35.467)

In [19]:
g7_pop.iloc[-1]

np.float64(318.523)

Selecting multiple elements at once:

In [21]:
g7_pop[['Italy', 'France']]  # the result is another Series

Italy     60.665
France    63.951
Name: G7 population in millions, dtype: float64

In [22]:
g7_pop.iloc[[0, 1]]

Canada    35.467
France    63.951
Name: G7 population in millions, dtype: float64

In Pandas the upper limit is also included

In [24]:
g7_pop['Canada': 'Italy']

Canada     35.467
France     63.951
Germany    80.940
Italy      60.665
Name: G7 population in millions, dtype: float64

---

##**Conditional selection (boolean arrays)**

In [25]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

In [28]:
g7_pop > 70  # o numpy verifica cada valor e retorna True ou False

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 population in millions, dtype: bool

In [29]:
g7_pop[g7_pop > 70]  # mostra os valores que atendem a condição

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 population in millions, dtype: float64

In [30]:
g7_pop.mean()

np.float64(107.30257142857144)

In [31]:
g7_pop[g7_pop > g7_pop.mean()]

Japan            127.061
United States    318.523
Name: G7 population in millions, dtype: float64

In [32]:
g7_pop.std()

97.24996987121581

In [33]:
g7_pop[(g7_pop > g7_pop.mean() - g7_pop.std() / 2) | (g7_pop > g7_pop.mean() + g7_pop.std() / 2)]

France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

---

##**Operations and methods**

In [34]:
g7_pop * 1_000_000

Canada             35467000.0
France             63951000.0
Germany            80940000.0
Italy              60665000.0
Japan             127061000.0
United Kingdom     64511000.0
United States     318523000.0
Name: G7 population in millions, dtype: float64

In [35]:
g7_pop.mean()

np.float64(107.30257142857144)

In [36]:
np.log(g7_pop)

Canada            3.568603
France            4.158117
Germany           4.393708
Italy             4.105367
Japan             4.844667
United Kingdom    4.166836
United States     5.763695
Name: G7 population in millions, dtype: float64

In [43]:
g7_pop['France':'Italy'].mean()

np.float64(68.51866666666666)

---

##**Boolean arrays**
(Work in the same way as NumPy)

In [44]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

In [45]:
g7_pop > 80

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 population in millions, dtype: bool

In [46]:
g7_pop[g7_pop > 80]

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 population in millions, dtype: float64

In [49]:
g7_pop[(g7_pop > 80) | (g7_pop < 40)]

Canada            35.467
Germany           80.940
Japan            127.061
United States    318.523
Name: G7 population in millions, dtype: float64

In [50]:
g7_pop[(g7_pop > 80) & (g7_pop < 200)]

Germany     80.940
Japan      127.061
Name: G7 population in millions, dtype: float64

---

##**Modifying series**

In [51]:
g7_pop['Canada'] = 40.5

In [52]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

In [53]:
g7_pop.iloc[-1] = 500

In [54]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     500.000
Name: G7 population in millions, dtype: float64

In [55]:
g7_pop[g7_pop < 70] = 99.99

In [56]:
g7_pop

Canada             99.990
France             99.990
Germany            80.940
Italy              99.990
Japan             127.061
United Kingdom     99.990
United States     500.000
Name: G7 population in millions, dtype: float64

---