<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/PandasConditionalSelectionandModifyingDataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    'GPD': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GPD', 'Surface Area', 'HDI', 'Continent'])

In [3]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [4]:
df

                Population       GPD  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

##**Conditional selection (boolean arrays)**

In [5]:
df['Population'] > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [6]:
df.loc[df['Population'] > 70]

               Population       GPD  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [7]:
df.loc[df['Population'] > 70, 'Population']

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [8]:
df.loc[df['Population'] > 70, ['Population', 'GPD']]

               Population       GPD
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

---

##**Dropping stuff**

Point which ones you'd like to `drop.`

In [9]:
df.drop('Canada')

                Population       GPD  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [10]:
df.drop(['Canada', 'Japan'])

                Population       GPD  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [11]:
df.drop(columns = ['Population', 'HDI'])

                     GPD  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [15]:
df.drop(['Italy', 'Canada'], axis = 0) # remove do DataFrame as linhas cujos índices são Italy e Canada.

                Population       GPD  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

Returns a new DataFrame

---

##**Modifying DataFrames**

###Adding a new column

In [16]:
langs = pd.Series (
    ['French', 'German', 'Italian'],
    index = ['France', 'Germany', 'Italy'],
    name = 'Language'
)

In [17]:
df['Language'] = langs

In [18]:
df

                Population       GPD  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

---

Replacing values per column

In [20]:
df['Language'] = 'English'

In [21]:
df

                Population       GPD  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

---

Renaming columns

In [28]:
# mudanças não permanentes

In [22]:
df.rename(
    columns = {
        'HDI': 'Human Development Index',
        'Anual Popcorn Consumption': 'APC'
    }, index = {
        'United States': 'USA',
        'United Kingdom': 'UK',
        'Argentina': 'AR'
    })

,Population,GPD,Surface Area,Human Development Index,Continent,Language
Canada,35.467,1785387,9984670,0.913,America,English
France,63.951,2833687,640679,0.888,Europe,English
Germany,80.940,3874437,357114,0.916,Europe,English
Italy,60.665,2167744,301336,0.873,Europe,English
Japan,127.061,4602367,377930,0.891,Asia,English
UK,64.511,2950039,242495,0.907,Europe,English
USA,318.523,17348075,9525067,0.915,America,English

In [24]:
df.rename(index = str.upper)

                Population       GPD  Surface Area    HDI Continent Language
CANADA              35.467   1785387       9984670  0.913   America  English
FRANCE              63.951   2833687        640679  0.888    Europe  English
GERMANY             80.940   3874437        357114  0.916    Europe  English
ITALY               60.665   2167744        301336  0.873    Europe  English
JAPAN              127.061   4602367        377930  0.891      Asia  English
UNITED KINGDOM      64.511   2950039        242495  0.907    Europe  English
UNITED STATES      318.523  17348075       9525067  0.915   America  English

In [25]:
df.rename(index = lambda x: x.lower())

                Population       GPD  Surface Area    HDI Continent Language
canada              35.467   1785387       9984670  0.913   America  English
france              63.951   2833687        640679  0.888    Europe  English
germany             80.940   3874437        357114  0.916    Europe  English
italy               60.665   2167744        301336  0.873    Europe  English
japan              127.061   4602367        377930  0.891      Asia  English
united kingdom      64.511   2950039        242495  0.907    Europe  English
united states      318.523  17348075       9525067  0.915   America  English