<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/ReadingHTMLtables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Reading HTML tables**

How to read and parse HTML tables from websites into a list of `DataFrame `objects to work with.

---

In [1]:
!pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (6.1.3)

In [2]:
import pandas as pd

##**Parsing raw HTML strings**
read_html() will read HTML tables from a URL, a file-like object or a raw string containing HTML, and return a list of DataFrame objects.

In [3]:
html_string = """
<table>
        <thead>
            <tr>
                <th>Sequence</th>
                <th>Country</th>
                <th>Population</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>China</td>
                <td>1,439,323,776</td>
                <td>1-Dec-2020</td>
            </tr>
            <tr>
                <td>2</td>
                <td>India</td>
                <td>1,380,004,385</td>
                <td>1-Dec-2020</td>
            </tr>
            <tr>
                <td>3</td>
                <td>United States</td>
                <td>331,002,651</td>
                <td>1-Dec-2020</td>
            </tr>
        </tbody>
    </table>
    """

In [4]:
from IPython.core.display import display, HTML
display(HTML(html_string))

In [5]:
dfs = pd.read_html(html_string)

/tmp/ipykernel_3884/2234146965.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(html_string)

The read_html just returner one `DataFrame` object:

In [6]:
len(dfs)

1

One website can have multiple tables.

In [8]:
df = dfs[0]

df

   Sequence        Country  Population     Updated
0         1          China  1439323776  1-Dec-2020
1         2          India  1380004385  1-Dec-2020
2         3  United States   331002651  1-Dec-2020

In [9]:
df.shape

(3, 4)

In [11]:
df.loc[df['Country'] == 'China']

   Sequence Country  Population     Updated
0         1   China  1439323776  1-Dec-2020

##**Defining header**

Pandas will automatically find the header to use thanks to the tag.

But in many cases we'll find wrong or incomplete tables that make the `read_html` method parse the tables in wrong way whithout the proper headers.

To fiz them we can use the `header` parameter.

In [12]:
html_string = """
<table>
        <thead>
            <tr>
                <th>Sequence</th>
                <th>Country</th>
                <th>Population</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>China</td>
                <td>1,439,323,776</td>
                <td>1-Dec-2020</td>
            </tr>
            <tr>
                <td>2</td>
                <td>India</td>
                <td>1,380,004,385</td>
                <td>1-Dec-2020</td>
            </tr>
            <tr>
                <td>3</td>
                <td>United States</td>
                <td>331,002,651</td>
                <td>1-Dec-2020</td>
            </tr>
        </tbody>
    </table>
    """

In [13]:
pd.read_html(html_string)[0]

/tmp/ipykernel_3884/2877898795.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(html_string)[0]

   Sequence        Country  Population     Updated
0         1          China  1439323776  1-Dec-2020
1         2          India  1380004385  1-Dec-2020
2         3  United States   331002651  1-Dec-2020

We'll need to pass the row number to use as header using the `header` parameter.

In [14]:
pd.read_html(html_string, header=0)[0]

/tmp/ipykernel_3884/3156000096.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(html_string, header=0)[0]

   Sequence        Country  Population     Updated
0         1          China  1439323776  1-Dec-2020
1         2          India  1380004385  1-Dec-2020
2         3  United States   331002651  1-Dec-2020

---

##**Paring HTML tables from the web**

Now that we know how to `read_html` works we can try to parse HTML tables directly from an URL.

To do that we'll call the `read_html `method with an URL as parameter.

**Simple example**

In [15]:
html_url = "https://www.basketball-reference.com/leagues/NBA_2019_per_game.html"

In [16]:
nba_tables = pd.read_html(html_url)

In [17]:
len(nba_tables)

2

Work with one table found

In [22]:
nba = nba_tables[0]

In [23]:
nba.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,James Harden,29.0,HOU,PG,78.0,78.0,36.8,10.8,24.5,...,0.8,5.8,6.6,7.5,2.0,0.7,5.0,3.1,36.1,"MVP-2,AS,NBA1"
1,2.0,Paul George,28.0,OKC,SF,77.0,77.0,36.9,9.2,21.0,...,1.4,6.8,8.2,4.1,2.2,0.4,2.7,2.8,28.0,"MVP-3,DPOY-3,AS,NBA1,DEF1"
2,3.0,Giannis Antetokounmpo,24.0,MIL,PF,72.0,72.0,32.8,10.0,17.3,...,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7,"MVP-1,DPOY-2,AS,NBA1,DEF1"
3,4.0,Joel Embiid,24.0,PHI,C,64.0,64.0,33.7,9.1,18.7,...,2.5,11.1,13.6,3.7,0.7,1.9,3.5,3.3,27.5,"MVP-7,DPOY-4,AS,NBA2,DEF2"
4,5.0,LeBron James,34.0,LAL,SF,55.0,55.0,35.2,10.1,19.9,...,1.0,7.4,8.5,8.3,1.3,0.6,3.6,1.7,27.4,"MVP-11,AS,NBA3"

**Complex example**

We can use the requests module to get HTML code from an URL to parse it into DataFrame objects.

We want to keep the table with information about each season.

In [39]:
for i, tabela in enumerate(wiki_tables):
    colunas = str(tabela.columns).lower()

    if "season" in colunas and "episodes" in colunas:
        print("Tabela encontrada:", i)
        display(tabela.head())

Tabela encontrada: 2

  Season          No. of episodes    Originally aired                   \
  Season          No. of episodes     Season premiere    Season finale
  Season Season.1 No. of episodes     Season premiere    Season finale
0      1  1989–90              13   December 17, 1989     May 13, 1990
1      2  1990–91              22    October 11, 1990    July 11, 1991
2      3  1991–92              24  September 19, 1991  August 27, 1992
3      4  1992–93              22  September 24, 1992     May 13, 1993
4      5  1993–94              22  September 30, 1993     May 19, 1994

                                                 Viewership  \
     Time slot (ET) Avg. households / viewers (in millions)
     Time slot (ET) Avg. households / viewers (in millions)
0    Sunday 8:30 pm                       13.4m h.[n1][128]
1  Thursday 8:00 pm                        12.2m h.[n1][n2]
2  Thursday 8:00 pm                          12m h.[n1][n3]
3  Thursday 8:00 pm                       12.1m h.[n1][132]
4  Thursday 8:00 pm                        10.5m h.[n1][n4]


  Most watched episode
    Viewers (millions)             Episode title
0            33.5[129]   "Life on the Fast Lane"
1            33.6[130]        "Bart Gets an 'F'"
2            25.5[131]           "Colonel Homer"
3            28.6[133]       "Lisa's First Word"
4            24.0[134]  "Treehouse of Horror IV"

In [43]:
import pandas as pd
import requests
from io import StringIO

html_url = "https://en.wikipedia.org/wiki/The_Simpsons"

headers = {"User-Agent": "Mozilla/5.0"}

r = requests.get(html_url, headers=headers)
r.raise_for_status()


wiki_tables = pd.read_html(StringIO(r.text), header=0)


simpsons = wiki_tables[2].copy()

simpsons.head()

,Season,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. of episodes,Season premiere,Season finale,Time slot (ET),Avg. households / viewers (in millions),Most watched episode,Most watched episode
1,Season,Season,No. of episodes,Season premiere,Season finale,Time slot (ET),Avg. households / viewers (in millions),Viewers (millions),Episode title
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][128],33.5[129],"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[130],"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[131],"""Colonel Homer"""

In [45]:
simpsons.drop([0, 1], inplace=True)

In [46]:
simpsons.set_index('Season', inplace=True)

Wich season  has the lowest number of episodes?

In [48]:
simpsons['No. of episodes'].unique()

array(['13', '22', '24', '25', '23', '21', '20', '18', '19', 'TBA'],
      dtype=object)

In [49]:
simpsons = simpsons.loc[simpsons['No. of episodes'] != 'TBA']

In [50]:
min_season = simpsons['No. of episodes'].min()

min_season

'13'

In [52]:
simpsons.loc[simpsons['No. of episodes'] == min_season]

,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][128],33.5[129],"""Life on the Fast Lane"""