<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/ReadingDataCSVandTXT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

#**Reading data with Pandas**

Probably one of the most recurrent types of work for data analysis: public data sources, logs, historical information tables, exports from databases. So the pandas library offers us functions to read and write files in multiple formats like CSV, JSON, XML and Excel's XLSX, all of them creating a `DataFrame` with the information read from the file.

We'll learn how to read different type of data including:

* CSV files (`.csv`)
* Raw text files (`.txt`)
* JSON data from a file and from an API
* Data from a SQL query over a database

There are many other available reading functions as the following table shows:

| Format Type | Data Description | Reader | Writer |
| :--- | :--- | :--- | :--- |
| text | CSV | `read_csv` | `to_csv` |
| text | JSON | `read_json` | `to_json` |
| text | HTML | `read_html` | `to_html` |
| text | Local clipboard | `read_clipboard` | `to_clipboard` |
| binary | MS Excel | `read_excel` | `to_excel` |
| binary | OpenDocument | `read_excel` | |
| binary | HDF5 Format | `read_hdf` | `to_hdf` |
| binary | Feather Format | `read_feather` | `to_feather` |
| binary | Parquet Format | `read_parquet` | `to_parquet` |
| binary | Msgpack | `read_msgpack` | `to_msgpack` |
| binary | Stata | `read_stata` | `to_stata` |
| binary | SAS | `read_sas` | |
| binary | Python Pickle Format | `read_pickle` | `to_pickle` |
| SQL | SQL | `read_sql` | `to_sql` |
| SQL | Google Big Query | `read_gbq` | `to_gbq` |

---

#**Reading our first CSV file**
Everytime we call `read_csv` method, we'll need to pass the `filepath `parameter indicatingn the path where our CSV file is.
For example, we can use read_csv method to load data directly from an URL:

In [9]:
csv_url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"

pd.read_csv(csv_url).head()

  Country Name Country Code  Year         Value
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09

Or just use a local file:

In [10]:
df = pd.read_csv("btc-market-price.csv")

df.head()

   2017-04-02 00:00:00  1099.169125
0  2017-04-03 00:00:00  1141.813000
1  2017-04-04 00:00:00  1141.600363
2  2017-04-05 00:00:00  1133.079314
3  2017-04-06 00:00:00  1196.307937
4  2017-04-07 00:00:00  1190.454250

In this case we let pandas infer everything related to our data, but in most of the cases we'll need to explicitly tell pandas how we want our data to be loaded. To do that we use parameters.
Let's see how theses parameters work.

---

##**First row behaviour with `header` parameter**

The CSV file we're reading has only two columns: `Timestamp` and `Price`. It doesn't have a header. Pandas automatically assigned the first row of the data as headers, which is incorrect. We can overwrite this behavior with the `header `parameter.

In [19]:
df = pd.read_csv("btc-market-price-2.csv",
                 header=None)

In [20]:
df.head()

             0            1
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00     1141.813
2  4/4/17 0:00            ?
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00            -

---
##**Missing values with `na_values` parameter**

We can define a na_values parameter with the values we want to be recognized as NA/NaN. In this case empty strings `''`, `?` and `-` will be recognized as null values.

In [21]:
df = pd.read_csv("btc-market-price-2.csv",
                 header=None,
                 na_values=['', '?', '-'])

In [22]:
df.head()

             0            1
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00  1141.813000
2  4/4/17 0:00          NaN
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00          NaN

---
##**Column names using `names` parameter
We'll add that columns names using the `names` parameter

In [23]:
df = pd.read_csv("btc-market-price-2.csv",
                 header=None,
                 na_values=['', '?', '-'],
                 names=["Timestamp", "Price"])

In [24]:
df.head()

     Timestamp        Price
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00  1141.813000
2  4/4/17 0:00          NaN
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00          NaN

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  365 non-null    object
 1   Price      354 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB

---
##**Column types using `dtype` parameter**
Without using the `dtype` parameter pandas will try to figure it out the type of each column. We can use `dtype `parameter to force pandas to use certain dtype.

In [26]:
df = pd.read_csv("btc-market-price-2.csv",
                 header=None,
                 na_values=['', '?', '-'],
                 names=["Timestamp", "Price"],
                 dtype={"Price": "float"})

In [27]:
df.head()

     Timestamp        Price
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00  1141.813000
2  4/4/17 0:00          NaN
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00          NaN

In [28]:
df.dtypes

Timestamp     object
Price        float64
dtype: object

We'll parse `Timestamp` column to `Datetime` objetcs using `to_datetime` method:

In [29]:
pd.to_datetime(df["Timestamp"]).head()

/tmp/ipykernel_1172/3786056407.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df["Timestamp"]).head()

0   2017-02-04
1   2017-03-04
2   2017-04-04
3   2017-05-04
4   2017-06-04
Name: Timestamp, dtype: datetime64[ns]

In [34]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"]) #converte os dados e sobrescreve a coluna original no DataFrame

In [31]:
df.head()

   Timestamp        Price
0 2017-02-04  1099.169125
1 2017-03-04  1141.813000
2 2017-04-04          NaN
3 2017-05-04  1133.079314
4 2017-06-04          NaN

In [32]:
df.dtypes

Timestamp    datetime64[ns]
Price               float64
dtype: object

---
##**Date parser using `parse_dates` parameter
Another way of dealing with `Datetime` objects is using `parse_dates` parameter with the position of the columns with dates.

In [33]:
df = pd.read_csv("btc-market-price-2.csv",
                 header=None,
                 na_values=['', '?', '-'],
                 names=["Timestamp", "Price"],
                 dtype={"Price": "float"},
                 parse_dates=[0])

/tmp/ipykernel_1172/3155119544.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("btc-market-price-2.csv",

In [35]:
df.dtypes

Timestamp    datetime64[ns]
Price               float64
dtype: object

---
##**Adding index to our data using `index_col` parameter
By default, pandas will automatically assign a numeric autoincremental index or row label starting with zero. You may want to leave the default index as such if your data doesn’t have a column with unique values that can serve as a better index. In case there is a column that you feel would serve as a better index, you can override the default behavior by setting index_col property to a column. It takes a numeric value representing the index or a string of the column name for setting a single column as index or a list of numeric values or strings for creating a multi-index.

In our data, we are choosing the first column, Timestamp, as index (index=0) by passing zero to the index_col argument.

In [36]:
df = pd.read_csv("btc-market-price-2.csv",
                 header=None,
                 na_values=['', '?', '-'],
                 names=["Timestamp", "Price"],
                 dtype={"Price": "float"},
                 parse_dates=[0],
                 index_col=[0])

/tmp/ipykernel_1172/487681294.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("btc-market-price-2.csv",

In [37]:
df.head()

                  Price
Timestamp
2017-02-04  1099.169125
2017-03-04  1141.813000
2017-04-04          NaN
2017-05-04  1133.079314
2017-06-04          NaN

In [38]:
df.dtypes

Price    float64
dtype: object

---
##**A more challenging parsing**
Now we'll read another CSV file. This file has the following columns:

* first_name
* last_name
* age
* math_score
* french_score
* next_test_date

Let's read it and see how it looks like.

In [39]:
exam_df = pd.read_csv("exam_review.csv")

In [40]:
exam_df

                               first_name>last_name>age>math_score>french_score
Ray>Morley>18>"68     000">"75                                             000"
Melvin>Scott>24>77>83 NaN                                                   NaN
Amirah>Haley>22>92>67 NaN                                                   NaN
Gerard>Mills>19>"78   000">72                                               NaN
Amy>Grimes>23>91>81   NaN                                                   NaN

---
##**Custom data delimiters using sep parameter**
We can define which delimiter to use by using the sep parameter. If we don't use the sep parameter, pandas will automatically detect the separator.

In most of the CSV files separator will be comma `(,)` and will be automatically detected. But we can find files with other separators like semicolon (`;)`, tabs (`\t`, specially on TSV files), whitespaces or any other special character.

In this case the separator is a` > `character.

In [41]:
exam_df = pd.read_csv("exam_review.csv",
                      sep=">")

In [42]:
exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

---
##**Custom data encoding**
Files are stored using different "encodings". You've probably heard about ASCII, UTF-8, latin1, etc.

While reading data custom encoding can be defined with the encoding parameter.

encoding='UTF-8': will be used if data is UTF-8 encoded.
encoding='iso-8859-1': will be used if data is ISO/IEC 8859-1 ("extended ASCII") encoded.
In our case we don't need a custom enconding as data is properly loaded

---
##**Custom numeric decimal and thousands character**
The decimal and thousands characters could change between datasets. If we have a column containing a comma (,) to indicate the decimal or thousands place, then this column would be considered a string and not numeric.

In [44]:
exam_df = pd.read_csv("exam_review.csv",
                      sep=">")

In [45]:
exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

In [47]:
exam_df[["math_score", "french_score"]].dtypes

math_score      object
french_score    object
dtype: object

To solve that, ensuring such columns are interpreted as integer values, we'll need to use the decimal and/or thousands parameters to indicate correct decimal and/or thousands indicators.

In [48]:
exam_df = pd.read_csv("exam_review.csv",
                      sep=">",
                      decimal=",")

In [49]:
exam_df

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18        68.0          75.0
1     Melvin     Scott   24        77.0          83.0
2     Amirah     Haley   22        92.0          67.0
3     Gerard     Mills   19        78.0          72.0
4        Amy    Grimes   23        91.0          81.0

In [50]:
exam_df[["math_score", "french_score"]].dtypes

math_score      float64
french_score    float64
dtype: object

Let's see what happens with the thousands parameter:

In [51]:
pd.read_csv("exam_review.csv",
            sep=">",
            thousands=",")

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18       68000         75000
1     Melvin     Scott   24          77            83
2     Amirah     Haley   22          92            67
3     Gerard     Mills   19       78000            72
4        Amy    Grimes   23          91            81

---
##**Excluding specific rows**
 We can use `skiprows` to:
* Exclude reading specified number of rows from the beginning of a file, by passing an integer argument. This removes the header too.
* Skip reading specific row indices from a file, by passing a list containing row indices to skip.

In [52]:
exam_df = pd.read_csv("exam_review.csv",
                      sep=">",
                      decimal=",")

In [53]:
exam_df

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18        68.0          75.0
1     Melvin     Scott   24        77.0          83.0
2     Amirah     Haley   22        92.0          67.0
3     Gerard     Mills   19        78.0          72.0
4        Amy    Grimes   23        91.0          81.0

To skip reading the first 2 rows from this file, we can use `skiprows=2`:

In [54]:
pd.read_csv("exam_review.csv",
            sep=">",
            skiprows=2)

   Melvin   Scott  24      77  83
0  Amirah   Haley  22      92  67
1  Gerard   Mills  19  78,000  72
2     Amy  Grimes  23      91  81

As the header is considered as the first row, to skip reading data rows 1 and 3, we can use `skiprows=[1,3]:`

In [56]:
exam_df = pd.read_csv("exam_review.csv",
                      sep=">",
                      decimal=",",
                      skiprows=[1,3])

In [57]:
exam_df

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81

---
##**Get rid of blank line**
The `skip_blank_lines` parameter is set to `True` so blank lines are skipped while we read files.

If we set this parameter to `False`, then every blank line will be loaded with `NaN` values into the `DataFrame`.

In [58]:
pd.read_csv("exam_review.csv",
            sep=">",
            skip_blank_lines=False)

  first_name last_name   age math_score french_score
0        Ray    Morley  18.0     68,000       75,000
1     Melvin     Scott  24.0         77           83
2     Amirah     Haley  22.0         92           67
3        NaN       NaN   NaN        NaN          NaN
4     Gerard     Mills  19.0     78,000           72
5        Amy    Grimes  23.0         91           81

---
##**Loading specific columns**
We can use the `usecols` parameter when we want to load just specific columns and not all of them.

Performance wise, it is better because instead of loading an entire dataframe into memory and then deleting the not required columns, we can select the columns that we’ll need, while loading the dataset itself.

As a parameter to usecols, you can pass either a list of strings corresponding to the column names or a list of integers corresponding to column index.

In [60]:
pd.read_csv("exam_review.csv",
            usecols=["first_name", "last_name", "age"],
            sep=">")

  first_name last_name  age
0        Ray    Morley   18
1     Melvin     Scott   24
2     Amirah     Haley   22
3     Gerard     Mills   19
4        Amy    Grimes   23

Or the position:

In [61]:
pd.read_csv("exam_review.csv",
            usecols=[0, 1, 2],
            sep=">")

  first_name last_name  age
0        Ray    Morley   18
1     Melvin     Scott   24
2     Amirah     Haley   22
3     Gerard     Mills   19
4        Amy    Grimes   23

---
##**Using a Series instead of DataFrame**
If the parsed data only contains one column then we can return a Series by setting the squeeze parameter to `True`.

In [64]:
exam_test_1 = pd.read_csv("exam_review.csv",
            sep=">",
            usecols=["last_name"])

In [66]:
type(exam_test_1)

pandas.core.frame.DataFrame

In [73]:
#transformar o resultado de apenas uma coluna em uma Series
exam_test_2 = pd.read_csv('exam_review.csv',
                          sep='>',
                          usecols=['last_name']).squeeze("columns")

In [74]:
type(exam_test_2)

pandas.core.series.Series

---
##**Save to CSV file**
Finally we can also save our DataFrame as a CSV file.

In [75]:
exam_df

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81

We can simply generate a CSV string from our DataFrame:

In [76]:
exam_df.to_csv()

',first_name,last_name,age,math_score,french_score\n0,Melvin,Scott,24,77.0,83\n1,Gerard,Mills,19,78.0,72\n2,Amy,Grimes,23,91.0,81\n'

Or specify a file path where we want our generated CSV code to be saved:

In [78]:
exam_df.to_csv("out.csv")

In [79]:
pd.read_csv("out.csv")

   Unnamed: 0 first_name last_name  age  math_score  french_score
0           0     Melvin     Scott   24        77.0            83
1           1     Gerard     Mills   19        78.0            72
2           2        Amy    Grimes   23        91.0            81

In [80]:
exam_df.to_csv("out.csv",
               index=None)

In [81]:
pd.read_csv("out.csv")

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81