<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/ReadingExcelFiles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
!head Products.xlsx

PK     ! �zғb  �   �[Content_Types].xml ��(�                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     �T�N�0�#���(q�!ԴG�|��7�UǶ����=��V�J���$�����{2�4.[CB|)��Hd�u0�/J����ߊIy�\�P�-��M//&o����R�D�NJ�54
&�U�\Evբ�	���d*�	���W��;����Q��az�8<n�o3�����F`�nؓϐ�!,��J�N�(�w���ӛ�Qr�'��r&�	�,�=;��lw�bDٽNo��j��<`X���ʳ��'���}:$8>�]g��	��>�~  �� PK     ! �U0#�   L   �_rels/.rels ��(�                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ���N�0��H�C���nH���LH�!T�$����$@����Jc�����?[���iTb/Nú(A�3b{�jx��V�b"gi��aW��l_x���b���������#b4O��r��0Q�ahѓ�eܔ�=��P-<��j{�>�<���4Mox/�}b�N�@�;�v�Cf��ۨ�B�I�����"c�&�\O���8q"K��H��<ߊs@��.�h����<⧄�Md�a��T_   �� PK     ! �>���   �   xl/_rels/workbook.xml.rels �(�                                                                                                                                                                                                                                                                 ���J�0����nӮ""��E��j}��L��m2㟾���ۅe���f���2���k�&�WP%�&��w
ޚ���[=�
&$���W�4�K��H"�xR��㣔d�����NҨ9��ɨ�Aw(7ey/���O��
��ނh�����m�|
�}D�g"$�4��F�Y��.2#���5�9��鳔�Y]b��d��@��%�s�"�ݚ0�tB��)���[����ȓ���  �� PK     ! h�8��  �     xl/workbook.xml�R�n�0��?�˔)~�rP�
�W��=$����z[�����V�Z�$�7A�Ω��J���2^gQ\^�Q�Z��*�J��쐖��<���7.�n._gdYsg�pߡ�s�˚!_�5����j�  �� PK     ! �M'+�  f     xl/sharedStrings.xml|XMs7��*��KN�HIT\)Y)���DI+�٪��p0��,�Ϥ��Cr�R����} e;0��3�ht�~��'�?���3m���F��a�P%�ի������1�ʒ
%٫і����_ub�%���ը���n�5k�y�:&�d�tK-��վ�4������?���[���I�s�q���W�fO�LG�'������JW�7?���ӓ}���h��GK�u�3�ͨe�����[�m��F�"q>�)7�1Y�f�9���Jހ��b��#�G&D�����%fg��J��j����#�阠����mș�J~cȌ�9I��%Q����K�;���Q�D򅧹k׊,�C���x�����Z� ^��arʹޒe�F�n��ˡ8��B0xY�׵����As��e��&D�I�T�E|֕Ҷ~�T�� ħ��K�sj�Kς����f�7.>g�s;�I���M�4M�|}�0���3��Q��Z�t&�	�%wޙ-�D�V�\RrC�U����}��:��?�_f�6ɻG���pV�L2 �Vn�؆�9x�7�^��$���m©�i�H�ڞ,�E����݈�_�r��Ւ�{%ɊW���zr<T������jU(�"��)����THv�)k,�&���l�&YPp��%��9�������D�
n�� | j�:�'�r�zbA�35�c�`�"CɅ�P�=2BVLp���?SM�xAMAu�,k������s\�-��\�.���Q[��L$m���	�E}�JK�F
ZAp!b����N��{ZAj=�L�����Jp���$�`��ψ��f�0�6m��[ �(H<�dL|��H,HzM`��y���W9V�-P�{G~���,�L��s�����Y�~�[���'�4�$?���P�A,Xr�0j>�T}��TMfj�I-1*>

##**Reading our first Excel file**

Everytime we call `read_excel` method, we need to pass an explicit `filepath` parameter indicating the path where our Excel file is.

In [4]:
df = pd.read_excel('Products.xlsx')

In [5]:
df.head()

,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,1,Chais,1,1,10 boxes x 20 bags,18.00
1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

---

##**Adding index to our data using index_col parameter**

By default, pandas will automatically assign a numeric autoincremental index or row label starting with zero.

You can override the default behavior by setting `index_col` property to a column.

In [6]:
df = pd.read_excel('Products.xlsx', index_col=0)

In [7]:
df.head()

,ProductName,SupplierID,CategoryID,Unit,Price
ProductID,,,,,
1,Chais,1,1,10 boxes x 20 bags,18.00
2,Chang,1,1,24 - 12 oz bottles,19.00
3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

---

##**Selecting specific sheets**

Excel files quite often have multiple sheets and the ability to read a specific sheet or all of them is very important. To make this easy, the pandas `read_excel` method takes an argument called `sheet_name` that tells pandas which sheet to read in the data from.   

For this, you can either use the sheet name or the sheet number. Sheet numbers start with zero. The first sheet will be the one loaded by default. You can change sheet by specifying `sheet_name` parameter.

In [8]:
products = pd.read_excel('Products.xlsx', sheet_name='Products', index_col='ProductID')
products.head()

,ProductName,SupplierID,CategoryID,Unit,Price
ProductID,,,,,
1,Chais,1,1,10 boxes x 20 bags,18.00
2,Chang,1,1,24 - 12 oz bottles,19.00
3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

---

##**The `ExcelFile` class**

Parsing tabular Excel sheets into DataFrame objects.

This `ExcelFile` will let us work with sheets easily, and will be faster than the previous read_excel method.

In [9]:
excel_file = pd.ExcelFile('Products.xlsx')

In [10]:
excel_file

We can now explore the sheets on that Excel file with `sheet_names`.

In [11]:
excel_file.sheet_names

['Products']

And parse specified sheet(s) into Panda's `DataFrame` using ExcelFile's `parse() `method.

We'll need to pass an explicit `sheet_name `parameter.

In [12]:
products = excel_file.parse('Products')

In [13]:
products.head()

,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,1,Chais,1,1,10 boxes x 20 bags,18.00
1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

In [14]:
products.dtypes

ProductID        int64
ProductName     object
SupplierID       int64
CategoryID       int64
Unit            object
Price          float64
dtype: object

---

##**Save to Excel file**

We can save our `DataFrame` as a Excel file.

In [15]:
products.head()

,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,1,Chais,1,1,10 boxes x 20 bags,18.00
1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

A fast and simple way to write a single `DataFrame` to an Excel file is to use the `to_excel()` method of the DataFrame directly.

It's required to pass a output file path.


> The openpyxl library should be installed in order to save Excel files. pip install `openpyxl`.

In [18]:
products.to_excel('out.xlsx')

In [19]:
pd.read_excel('out.xlsx').head()

,Unnamed: 0,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,0,1,Chais,1,1,10 boxes x 20 bags,18.00
1,1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

By removing the index we'll loose thtat column.

In [20]:
products.to_excel('out.xlsx', index=None)

In [21]:
pd.read_excel('out.xlsx').head()

,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,1,Chais,1,1,10 boxes x 20 bags,18.00
1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

---

##**Positioning Data with `startrow `and `startcol`**

In [22]:
products.to_excel('out.xlsx', startrow=1, startcol=2)

---

##**Saving multiple sheets**

If we wanted to write a single `DataFrame` to a single sheet with default formatting then we are done. However, if we want to write multiple sheets and/or multiple `DataFrame`s, then we will need to create an `ExcelWriter` objec.

The `ExcelWriter` object is included in the Pandas module and is used to open Excel files and handle write operations. This object behaves almost exactly like the vanilla Python `open` object that we used on previous courses and can be used within a `with` block.

> When the `ExcelWriter` object is executed, any existing file with the same name as the output file will be overwritten.

In [25]:
writer = pd.ExcelWriter('out.xlsx')

In [26]:
writer

Instead of including the file pathname in the `to_excel` call, we will use the `ExcelWriter` object `writer` instead.

In [27]:
with writer:
  products.to_excel(writer, sheet_name='Products')

In [29]:
pd.read_excel('out.xlsx', sheet_name='Products').head()

,Unnamed: 0,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,0,1,Chais,1,1,10 boxes x 20 bags,18.00
1,1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

We can now add another `Merchants` sheet simply using the `writer` object.

In [ ]:
with writer:
    merchants.to_excel(writer, sheet_name='Merchants') #exemplo sem tabela aqui

In [31]:
pd.read_excel('out.xlsx', sheet_name='Products').head()

,Unnamed: 0,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,0,1,Chais,1,1,10 boxes x 20 bags,18.00
1,1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

In [ ]:
pd.read_excel('out.xlsx', sheet_name='Merchants').head()

Or we can save multiple sheets at the same time:

In [ ]:
with pd.ExcelWriter('out.xlsx') as writer:
    products.to_excel(writer, sheet_name='Products')
    merchants.to_excel(writer, sheet_name='Merchants')