<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/TextHandling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd

##**Text Handling**

Cleaning text values can be incredibly hard. Invalid text values involves, 99% of the time, mistyping, which is completely unpredictable and doesn't follow any pattern. Thankfully, it's not so common these days, where data-entry tasks have been replaced by machines. Still, let's explore the most common cases

##**Splitting Columns**

The result of a survey is loaded and this is what you get:

In [17]:
df = pd.DataFrame({
    'Data': [
        '1987_M_US _1',
        '1990?_M_UK_1',
        '1992_F_US_2',
        '1970?_M_   IT_1',
        '1985_F_I  T_2'
]})

In [18]:
df

              Data
0     1987_M_US _1
1     1990?_M_UK_1
2      1992_F_US_2
3  1970?_M_   IT_1
4    1985_F_I  T_2

In [19]:
df.info()   #object = string

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    5 non-null      object
dtypes: object(1)
memory usage: 172.0+ bytes

You know that the single columns represent the values "year, Sex, Country and number of children", but it's all been grouped in the sam ecolumn and separated by an underscore. Pandas has a convenient method named `split` that we can use in these situations:

In [20]:
df['Data'].str.split('_')

0       [1987, M, US , 1]
1       [1990?, M, UK, 1]
2        [1992, F, US, 2]
3    [1970?, M,    IT, 1]
4      [1985, F, I  T, 2]
Name: Data, dtype: object

In [21]:
# divide os textos da coluna 'Data' onde houver "_" e separa cada parte em novas colunas
# cria um novo DataFrame
df = df['Data'].str.split('_', expand=True)

In [22]:
df.columns = ['Year', 'Sex', 'Country', 'No Children']

In [23]:
df

    Year Sex Country No Children
0   1987   M     US            1
1  1990?   M      UK           1
2   1992   F      US           2
3  1970?   M      IT           1
4   1985   F    I  T           2

In [24]:
df['Year'].str.contains('/?')

0    True
1    True
2    True
3    True
4    True
Name: Year, dtype: bool

`contains` takes a regex/pattern as first value, so we need to escape the ? symbol as it has a special meaning for these patters. Regular letters don't need escaping:

In [25]:
df['Country'].str.contains('U')

0     True
1     True
2     True
3    False
4    False
Name: Country, dtype: bool

Removing blank spaces (like in `'US'` or `'I  T'`) can be achieved with `strip`(`lstrip` and `rstrip` also exist) or just replace:

In [27]:
df['Country'].str.strip()  #remover espaço

0      US
1      UK
2      US
3      IT
4    I  T
Name: Country, dtype: object

In [28]:
df['Country'].str.replace(' ', '')

0    US
1    UK
2    US
3    IT
4    IT
Name: Country, dtype: object

`replace `and `contains` take regex patterns, wich can make it easier to replace values in bulk:

In [32]:
df['Year'].str.replace(r'(?P<year>\d{4})\?', lambda m: m.group('year'), regex=True)

# (?P<year>   )   → cria um grupo chamado "year"
# \d              → qualquer número de 0 a 9
# {4}             → exatamente 4 números
# \?              → o caractere ? literalmente

# A palavra lambda serve para criar uma função curta sem precisar dar nome a ela.

0    1987
1    1990
2    1992
3    1970
4    1985
Name: Year, dtype: object

> Some people, when confronted with a problem, think "I know, I'll use regular expression". Now they have two problems.

As you can see, all these string/text operations are applied over the `str `attribute of the series. That's because they have a special place in Series handling.

---